//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTour.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingTour.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string Bài_viết {
            get {
                return ResourceManager.GetString("Bài viết", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn địa điểm đến.
        /// </summary>
        public static string Chọn_địa_điểm_đến {
            get {
                return ResourceManager.GetString("Chọn địa điểm đến", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đăng ký làm nhà cung cấp.
        /// </summary>
        public static string đăng_ký_làm_nhà_cung_cấp {
            get {
                return ResourceManager.GetString("đăng ký làm nhà cung cấp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đén phổ biến.
        /// </summary>
        public static string Điểm_đén_phổ_biến {
            get {
                return ResourceManager.GetString("Điểm đén phổ biến", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du thuyền.
        /// </summary>
        public static string Du_thuyền {
            get {
                return ResourceManager.GetString("Du thuyền", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãng hàng không.
        /// </summary>
        public static string Hãng_hàng_không {
            get {
                return ResourceManager.GetString("Hãng hàng không", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn.
        /// </summary>
        public static string Hóa_đơn {
            get {
                return ResourceManager.GetString("Hóa đơn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động giải trí ngoài trời.
        /// </summary>
        public static string Hoạt_động_giải_trí_ngoài_trời {
            get {
                return ResourceManager.GetString("Hoạt động giải trí ngoài trời", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách sạn.
        /// </summary>
        public static string Khách_sạn {
            get {
                return ResourceManager.GetString("Khách sạn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi &amp; Giảm giá đặc biệt.
        /// </summary>
        public static string Khuyến_mãi___Giảm_giá_đặc_biệt {
            get {
                return ResourceManager.GetString("Khuyến mãi & Giảm giá đặc biệt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử đặt.
        /// </summary>
        public static string Lịch_sử_đặt {
            get {
                return ResourceManager.GetString("Lịch sử đặt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một con sông nhỏ tên Duden chảy qua nơi này và cung cấp cho họ những thứ cần thiết. Đây là một quốc gia như thiên đường, nơi mà những phần câu đã nướng chảy vào miệng bạn..
        /// </summary>
        public static string Một_con_sông_nhỏ_tên_Duden_chảy_qua_nơi_này_và_cung_cấp_cho_họ_những_thứ_cần_thiết__Đây_là_một_quốc_gia_như_thiên_đường__nơi_mà_những_phần_câu_đã_nướng_chảy_vào_miệng_bạn_ {
            get {
                return ResourceManager.GetString("Một con sông nhỏ tên Duden chảy qua nơi này và cung cấp cho họ những thứ cần thiế" +
                        "t. Đây là một quốc gia như thiên đường, nơi mà những phần câu đã nướng chảy vào " +
                        "miệng bạn.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chuyến đi.
        /// </summary>
        public static string Số_chuyến_đi {
            get {
                return ResourceManager.GetString("Số chuyến đi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng khách hàng.
        /// </summary>
        public static string Số_lượng_khách_hàng {
            get {
                return ResourceManager.GetString("Số lượng khách hàng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhân viên.
        /// </summary>
        public static string Số_lượng_nhân_viên {
            get {
                return ResourceManager.GetString("Số lượng nhân viên", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng quốc gia.
        /// </summary>
        public static string Số_lượng_quốc_gia {
            get {
                return ResourceManager.GetString("Số lượng quốc gia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuê xe.
        /// </summary>
        public static string Thuê_xe {
            get {
                return ResourceManager.GetString("Thuê xe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Tìm_kiếm {
            get {
                return ResourceManager.GetString("Tìm kiếm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trải nghiệm kỳ nghĩ tuyệt vời Ở.
        /// </summary>
        public static string Trải_nghiệm_kỳ_nghĩ_tuyệt_vời_Ở {
            get {
                return ResourceManager.GetString("Trải nghiệm kỳ nghĩ tuyệt vời Ở", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cá nhân.
        /// </summary>
        public static string Trang_cá_nhân {
            get {
                return ResourceManager.GetString("Trang cá nhân", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Trang_chủ {
            get {
                return ResourceManager.GetString("Trang chủ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xã xa, đằng sau những ngọn núi chữ, xa khỏi các quốc gia Vokalia và Consonantia, có những văn bản mù sống. Tách biệt chúng sống trong Bookmarksgrove ngay tại bờ biển của Semantics, một đại dương ngôn ngữ rộng lớn..
        /// </summary>
        public static string Xã_xa__đằng_sau_những_ngọn_núi_chữ__xa_khỏi_các_quốc_gia_Vokalia_và_Consonantia__có_những_văn_bản_mù_sống__Tách_biệt_chúng_sống_trong_Bookmarksgrove_ngay_tại_bờ_biển_của_Semantics__một_đại_dương_ngôn_ngữ_rộng_lớn_ {
            get {
                return ResourceManager.GetString("Xã xa, đằng sau những ngọn núi chữ, xa khỏi các quốc gia Vokalia và Consonantia, " +
                        "có những văn bản mù sống. Tách biệt chúng sống trong Bookmarksgrove ngay tại bờ " +
                        "biển của Semantics, một đại dương ngôn ngữ rộng lớn.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xa xôi, sau những dãy núi từ những quốc gia Vokalia và Consonantia, có những văn bản mù. Chúng sống tách biệt ở Bookmarksgrove ngay tại bờ biển của Semantics, một đại dương ngôn ngữ rộng lớn..
        /// </summary>
        public static string Xa_xôi__sau_những_dãy_núi_từ_những_quốc_gia_Vokalia_và_Consonantia__có_những_văn_bản_mù__Chúng_sống_tách_biệt_ở_Bookmarksgrove_ngay_tại_bờ_biển_của_Semantics__một_đại_dương_ngôn_ngữ_rộng_lớn_ {
            get {
                return ResourceManager.GetString("Xa xôi, sau những dãy núi từ những quốc gia Vokalia và Consonantia, có những văn " +
                        "bản mù. Chúng sống tách biệt ở Bookmarksgrove ngay tại bờ biển của Semantics, mộ" +
                        "t đại dương ngôn ngữ rộng lớn.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Video Tour.
        /// </summary>
        public static string Xem_Video_Tour {
            get {
                return ResourceManager.GetString("Xem Video Tour", resourceCulture);
            }
        }
    }
}
